export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const GET_VIDEOGAME_BY_NAME = 'GET_VIDEOGAME_BY_NAME'; 
export const GET_DETAIL= 'GET_DETAIL';
export const GET_GENRES = 'GET_GENRES';
export const FILTERED_BY_GENRES = 'FILTERED_BY_GENRES';
export const FILTERED_BY_ORIGIN= 'FILTERED_BY_ORIGIN'; 
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_RATING= 'ORDER_BY_RATING';
export const VIDEOGAME_CREATED='VIDEOGAME_CREATED';





